version: "3"
services:
    asyn_api_func_test:
        build:
            context: ./tests
        image: videoserv-async-api-func-test:1.0.0
        environment:
            - ELASTIC_HOST=elasticsearch
            - ELASTIC_PORT=9200
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - API_HOST=async_api
            - API_PORT=8888
            - PYTHONDONTWRITEBYTECODE=1
        working_dir: /opt/async_api/tests
        command: >
            wait-for-it
                --service redis:6379
                --service elasticsearch:9200
                --timeout 30
                -- pytest -p no:cacheprovider --capture=no ./functional/src
        volumes:
            - ./tests:/opt/async_api/tests
networks:
    default:
        external:
            name: videoserv_net
